/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: auth_struct.proto */

#ifndef PROTOBUF_C_auth_5fstruct_2eproto__INCLUDED
#define PROTOBUF_C_auth_5fstruct_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AuthenticateSolicitation AuthenticateSolicitation;
typedef struct _AuthenticateResponse AuthenticateResponse;
typedef struct _AuthenticateAcknowledgement AuthenticateAcknowledgement;
typedef struct _RegisterSolicitation RegisterSolicitation;
typedef struct _RegisterResponse RegisterResponse;
typedef struct _ConnectionSolicitation ConnectionSolicitation;
typedef struct _ConnectionResponse ConnectionResponse;
typedef struct _ConnectionAcknowledgement ConnectionAcknowledgement;


/* --- enums --- */


/* --- messages --- */

struct  _AuthenticateSolicitation
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *usr;
  char *pw;
};
#define AUTHENTICATE_SOLICITATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&authenticate_solicitation__descriptor) \
    , 0,0, NULL, NULL }


struct  _AuthenticateResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *token;
};
#define AUTHENTICATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&authenticate_response__descriptor) \
    , 0,0, NULL }


struct  _AuthenticateAcknowledgement
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *token;
};
#define AUTHENTICATE_ACKNOWLEDGEMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&authenticate_acknowledgement__descriptor) \
    , 0,0, NULL }


struct  _RegisterSolicitation
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *token;
};
#define REGISTER_SOLICITATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&register_solicitation__descriptor) \
    , 0,0, NULL }


struct  _RegisterResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *token;
  char *regnr;
};
#define REGISTER_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&register_response__descriptor) \
    , 0,0, NULL, NULL }


struct  _ConnectionSolicitation
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *token;
  char *regnr;
};
#define CONNECTION_SOLICITATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connection_solicitation__descriptor) \
    , 0,0, NULL, NULL }


struct  _ConnectionResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  protobuf_c_boolean has_ip;
  uint32_t ip;
  protobuf_c_boolean has_port;
  uint32_t port;
};
#define CONNECTION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connection_response__descriptor) \
    , 0,0, 0,0, 0,0 }


struct  _ConnectionAcknowledgement
{
  ProtobufCMessage base;
  protobuf_c_boolean has_header;
  int32_t header;
  char *token;
  protobuf_c_boolean has_ip;
  uint32_t ip;
  protobuf_c_boolean has_port;
  uint32_t port;
};
#define CONNECTION_ACKNOWLEDGEMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connection_acknowledgement__descriptor) \
    , 0,0, NULL, 0,0, 0,0 }


/* AuthenticateSolicitation methods */
void   authenticate_solicitation__init
                     (AuthenticateSolicitation         *message);
size_t authenticate_solicitation__get_packed_size
                     (const AuthenticateSolicitation   *message);
size_t authenticate_solicitation__pack
                     (const AuthenticateSolicitation   *message,
                      uint8_t             *out);
size_t authenticate_solicitation__pack_to_buffer
                     (const AuthenticateSolicitation   *message,
                      ProtobufCBuffer     *buffer);
AuthenticateSolicitation *
       authenticate_solicitation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   authenticate_solicitation__free_unpacked
                     (AuthenticateSolicitation *message,
                      ProtobufCAllocator *allocator);
/* AuthenticateResponse methods */
void   authenticate_response__init
                     (AuthenticateResponse         *message);
size_t authenticate_response__get_packed_size
                     (const AuthenticateResponse   *message);
size_t authenticate_response__pack
                     (const AuthenticateResponse   *message,
                      uint8_t             *out);
size_t authenticate_response__pack_to_buffer
                     (const AuthenticateResponse   *message,
                      ProtobufCBuffer     *buffer);
AuthenticateResponse *
       authenticate_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   authenticate_response__free_unpacked
                     (AuthenticateResponse *message,
                      ProtobufCAllocator *allocator);
/* AuthenticateAcknowledgement methods */
void   authenticate_acknowledgement__init
                     (AuthenticateAcknowledgement         *message);
size_t authenticate_acknowledgement__get_packed_size
                     (const AuthenticateAcknowledgement   *message);
size_t authenticate_acknowledgement__pack
                     (const AuthenticateAcknowledgement   *message,
                      uint8_t             *out);
size_t authenticate_acknowledgement__pack_to_buffer
                     (const AuthenticateAcknowledgement   *message,
                      ProtobufCBuffer     *buffer);
AuthenticateAcknowledgement *
       authenticate_acknowledgement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   authenticate_acknowledgement__free_unpacked
                     (AuthenticateAcknowledgement *message,
                      ProtobufCAllocator *allocator);
/* RegisterSolicitation methods */
void   register_solicitation__init
                     (RegisterSolicitation         *message);
size_t register_solicitation__get_packed_size
                     (const RegisterSolicitation   *message);
size_t register_solicitation__pack
                     (const RegisterSolicitation   *message,
                      uint8_t             *out);
size_t register_solicitation__pack_to_buffer
                     (const RegisterSolicitation   *message,
                      ProtobufCBuffer     *buffer);
RegisterSolicitation *
       register_solicitation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   register_solicitation__free_unpacked
                     (RegisterSolicitation *message,
                      ProtobufCAllocator *allocator);
/* RegisterResponse methods */
void   register_response__init
                     (RegisterResponse         *message);
size_t register_response__get_packed_size
                     (const RegisterResponse   *message);
size_t register_response__pack
                     (const RegisterResponse   *message,
                      uint8_t             *out);
size_t register_response__pack_to_buffer
                     (const RegisterResponse   *message,
                      ProtobufCBuffer     *buffer);
RegisterResponse *
       register_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   register_response__free_unpacked
                     (RegisterResponse *message,
                      ProtobufCAllocator *allocator);
/* ConnectionSolicitation methods */
void   connection_solicitation__init
                     (ConnectionSolicitation         *message);
size_t connection_solicitation__get_packed_size
                     (const ConnectionSolicitation   *message);
size_t connection_solicitation__pack
                     (const ConnectionSolicitation   *message,
                      uint8_t             *out);
size_t connection_solicitation__pack_to_buffer
                     (const ConnectionSolicitation   *message,
                      ProtobufCBuffer     *buffer);
ConnectionSolicitation *
       connection_solicitation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connection_solicitation__free_unpacked
                     (ConnectionSolicitation *message,
                      ProtobufCAllocator *allocator);
/* ConnectionResponse methods */
void   connection_response__init
                     (ConnectionResponse         *message);
size_t connection_response__get_packed_size
                     (const ConnectionResponse   *message);
size_t connection_response__pack
                     (const ConnectionResponse   *message,
                      uint8_t             *out);
size_t connection_response__pack_to_buffer
                     (const ConnectionResponse   *message,
                      ProtobufCBuffer     *buffer);
ConnectionResponse *
       connection_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connection_response__free_unpacked
                     (ConnectionResponse *message,
                      ProtobufCAllocator *allocator);
/* ConnectionAcknowledgement methods */
void   connection_acknowledgement__init
                     (ConnectionAcknowledgement         *message);
size_t connection_acknowledgement__get_packed_size
                     (const ConnectionAcknowledgement   *message);
size_t connection_acknowledgement__pack
                     (const ConnectionAcknowledgement   *message,
                      uint8_t             *out);
size_t connection_acknowledgement__pack_to_buffer
                     (const ConnectionAcknowledgement   *message,
                      ProtobufCBuffer     *buffer);
ConnectionAcknowledgement *
       connection_acknowledgement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connection_acknowledgement__free_unpacked
                     (ConnectionAcknowledgement *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AuthenticateSolicitation_Closure)
                 (const AuthenticateSolicitation *message,
                  void *closure_data);
typedef void (*AuthenticateResponse_Closure)
                 (const AuthenticateResponse *message,
                  void *closure_data);
typedef void (*AuthenticateAcknowledgement_Closure)
                 (const AuthenticateAcknowledgement *message,
                  void *closure_data);
typedef void (*RegisterSolicitation_Closure)
                 (const RegisterSolicitation *message,
                  void *closure_data);
typedef void (*RegisterResponse_Closure)
                 (const RegisterResponse *message,
                  void *closure_data);
typedef void (*ConnectionSolicitation_Closure)
                 (const ConnectionSolicitation *message,
                  void *closure_data);
typedef void (*ConnectionResponse_Closure)
                 (const ConnectionResponse *message,
                  void *closure_data);
typedef void (*ConnectionAcknowledgement_Closure)
                 (const ConnectionAcknowledgement *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor authenticate_solicitation__descriptor;
extern const ProtobufCMessageDescriptor authenticate_response__descriptor;
extern const ProtobufCMessageDescriptor authenticate_acknowledgement__descriptor;
extern const ProtobufCMessageDescriptor register_solicitation__descriptor;
extern const ProtobufCMessageDescriptor register_response__descriptor;
extern const ProtobufCMessageDescriptor connection_solicitation__descriptor;
extern const ProtobufCMessageDescriptor connection_response__descriptor;
extern const ProtobufCMessageDescriptor connection_acknowledgement__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_auth_5fstruct_2eproto__INCLUDED */
